name: Test Self-Hosted Runner

on:
  push:
    branches:
      - master

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Print Runner Namer
        run: echo "Running on $(hostname)"
