name: SonarQube Analysis

on:
  # Trigger analysis when pushing to your main branches, or when creating a pull request.
  push:
    branches:
      - develop

jobs:
  sonarqube:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
        fetch-depth: 0

    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"

    - name: Install dependencies
      run: yarn install --frozen-lockfile


    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2.3.0 # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
